### ISSUE TITLE
get rid of connection sharing

### ISSUE THREAD

**Issue by schmir** [trustlines-network/relay#197]
I've got the following error while running clientlib end2end tests.

Postgresql connections cannot be shared. See #142 

Here's the log output:
```
Error closing cursor
Traceback (most recent call last):
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: execute cannot be used while an asynchronous query is underway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _safe_close_cursor
    cursor.close()
psycopg2.ProgrammingError: close cannot be used while an asynchronous query is underway
Traceback (most recent call last):
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: execute cannot be used while an asynchronous query is underway

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/ralf/trustlines/relay/relay/blockchain/proxy.py", line 42, in watch_filter
    get_new_entries(filter, callback)
  File "/home/ralf/trustlines/relay/relay/blockchain/proxy.py", line 37, in get_new_entries
    callback(event)
  File "/home/ralf/trustlines/relay/relay/blockchain/exchange_proxy.py", line 65, in log
    log_entry['args']['filledTakerTokenAmount'])
  File "/home/ralf/trustlines/relay/relay/exchange/exchange_db.py", line 168, in order_filled
    order_orm = self.session.query(OrderORM).filter_by(msg_hash=order_hash.hex()).first()
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2888, in first
    ret = list(self[0:1])
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2680, in __getitem__
    return list(res)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ralf/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) execute cannot be used while an asynchronous query is underway [SQL: 'SELECT orders.exchange_address AS orders_exchange_address, orders.maker_address AS orders_maker_address, orders.taker_address AS orders_taker_address, orders.maker_token AS orders_maker_token, orders.taker_token AS orders_taker_token, orders.fee_recipient AS orders_fee_recipient, orders.maker_token_amount AS orders_maker_token_amount, orders.taker_token_amount AS orders_taker_token_amount, orders.filled_maker_token_amount AS orders_filled_maker_token_amount, orders.filled_taker_token_amount AS orders_filled_taker_token_amount, orders.cancelled_maker_token_amount AS orders_cancelled_maker_token_amount, orders.cancelled_taker_token_amount AS orders_cancelled_taker_token_amount, orders.price AS orders_price, orders.maker_fee AS orders_maker_fee, orders.taker_fee AS orders_taker_fee, orders.expiration_timestamp_in_sec AS orders_expiration_timestamp_in_sec, orders.salt AS orders_salt, orders.v AS orders_v, orders.r AS orders_r, orders.s AS orders_s, orders.msg_hash AS orders_msg_hash \nFROM orders \nWHERE orders.msg_hash = %(msg_hash_1)s \n LIMIT %(param_1)s'] [parameters: {'msg_hash_1': '06b163006a49a60b72dce6f1c0c229dcdd5a92b65337fbf5e2576f94ce88d48b', 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)
2018-09-12T15:19:42Z <Greenlet "Greenlet-0" at 0x7f78aec0e148: watch_filter(<web3.utils.filters.LogFilter object at 0x7f78aebb, <function ExchangeProxy.start_listen_on_fill.<loca)> failed with ProgrammingError
```

**Comment by berndbohmeier** [comment]
Fixed in cd299e7
