### ISSUE TITLE
end2end tests fail for close trustline

### ISSUE THREAD

**Issue by schmir** [trustlines-network/relay#225]
```
1 ~/trustlines/clientlib (git)-[develop] % mocha --timeout 30000 --require isomorphic-fetch -r ts-node/register tests/e2e/Trustline.test.ts -g prepareClose
Random numbers will not be cryptographically secure


  e2e
    Trustline
      #prepareClose()
        ✓ should be possible to prepare a close in the correct direction. (116ms)
        1) should sign and relay prepared close transaction


  1 passing (14s)
  1 failing

  1) e2e
       Trustline
         #prepareClose()
           should sign and relay prepared close transaction:

      AssertionError: expected '-100' to equal '0'
      + expected - actual

      --100
      +0
      
      at Object.<anonymous> (tests/e2e/Trustline.test.ts:480:48)
      at step (tests/e2e/Trustline.test.ts:32:23)
      at Object.next (tests/e2e/Trustline.test.ts:13:53)
      at fulfilled (tests/e2e/Trustline.test.ts:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by schmir** [comment]
that's fixed in d47d287a39cab7b264fdefc4248fd9c91886b1f6 (currently only part of PR #224)
