### ISSUE TITLE
Investigate why populus is needed

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/relay#90]
In PR #88 we had to include the following line 
https://github.com/trustlines-network/relay/blob/develop/.travis.yml#L6
and
https://github.com/trustlines-network/relay/blob/develop/Dockerfile#L14
Because of this error:
```
...
  Running setup.py bdist_wheel for trustlines-contracts ... error
  Complete output from command /home/ralf/tt/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-94xhpk_2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-lkwjhgdb --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/tlcontracts
  copying tlcontracts/signing.py -> build/lib/tlcontracts
  copying tlcontracts/deploy.py -> build/lib/tlcontracts
  copying tlcontracts/__init__.py -> build/lib/tlcontracts
  copying tlcontracts/exchange.py -> build/lib/tlcontracts
  running compile_contracts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-94xhpk_2/setup.py", line 149, in <module>
      'build_py': BuildPyCommand,
    File "/home/ralf/tt/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/ralf/tt/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-94xhpk_2/setup.py", line 31, in run
      self.run_command('compile_contracts')
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/stow/python-3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-94xhpk_2/setup.py", line 45, in run
      from populus import Project
  ModuleNotFoundError: No module named 'populus'
  
  ----------------------------------------
  Failed building wheel for trustlines-contracts
  Running setup.py clean for trustlines-contracts
Successfully built cytoolz gevent geventhttpclient networkx pygraphviz SQLAlchemy
Failed to build trustlines-contracts
Installing collected packages: aniso8601, anyconfig, argh, bitcoin, certifi, pycparser, cffi, chardet, click, contextlib2, coverage, toolz, cytoolz, decorator, pysha3, eth-utils, eth-abi, eth-keys, semantic-version, rlp, eth-tester, Werkzeug, json-rpc, secp256k1, repoze.lru, scrypt, pyethash, PyYAML, pycryptodome, pbkdf2, ethereum, eth-testrpc, pyflakes, pycodestyle, mccabe, flake8, MarkupSafe, Jinja2, itsdangerous, Flask, six, Flask-Cors, pytz, Flask-RESTful, greenlet, gevent, gevent-websocket, Flask-Sockets, geventhttpclient, idna, jsonschema, lru-dict, marshmallow, typed-ast, mypy, networkx, pathtools, toposort, py-geth, py-solc, pylru, py, pytest, urllib3, requests, web3, watchdog, populus, pygraphviz, SQLAlchemy, tinyrpc, webargs, trustlines-contracts
  Running setup.py install for trustlines-contracts ... done
Successfully installed Flask-0.12.2 Flask-Cors-3.0.3 Flask-RESTful-0.3.6 Flask-Sockets-0.2.1 Jinja2-2.10 MarkupSafe-1.0 PyYAML-3.12 SQLAlchemy-1.2.7 Werkzeug-0.14.1 aniso8601-3.0.0 anyconfig-0.9.4 argh-0.26.2 bitcoin-1.1.42 certifi-2018.4.16 cffi-1.11.5 chardet-3.0.4 click-6.7 contextlib2-0.5.5 coverage-4.5.1 cytoolz-0.9.0.1 decorator-4.3.0 eth-abi-0.5.0 eth-keys-0.1.0b4 eth-tester-0.1.0b11 eth-testrpc-1.3.3 eth-utils-0.7.4 ethereum-1.6.1 flake8-3.5.0 gevent-1.1.2 gevent-websocket-0.10.1 geventhttpclient-1.3.1 greenlet-0.4.13 idna-2.6 itsdangerous-0.24 json-rpc-1.10.8 jsonschema-2.6.0 lru-dict-1.1.6 marshmallow-2.15.0 mccabe-0.6.1 mypy-0.590 networkx-2.1 pathtools-0.1.2 pbkdf2-1.3 populus-2.2.0 py-1.5.3 py-geth-2.0.1 py-solc-2.1.0 pycodestyle-2.3.1 pycparser-2.18 pycryptodome-3.6.1 pyethash-0.1.27 pyflakes-1.6.0 pygraphviz-1.3.1 pylru-1.0.9 pysha3-1.0.2 pytest-3.2.5 pytz-2018.4 repoze.lru-0.7 requests-2.18.4 rlp-0.6.0 scrypt-0.8.6 secp256k1-0.13.2 semantic-version-2.6.0 six-1.11.0 tinyrpc-0.8 toolz-0.9.0 toposort-1.5 trustlines-contracts-0.0.1.dev1 typed-ast-1.1.0 urllib3-1.22 watchdog-0.8.3 web3-3.16.5 webargs-2.1.0
```
We should check why this is necessary and maybe fix it in contracts rep.

**Comment by schmir** [comment]
Another related problem is that building source distributions doesn't work.  We also should fix that.

The contracts repo's setup.py imports populus in order to build the contracts. If we install from the git repository and don't add the compiled contracts to the git repository, there's no way around having populus installed. setup_requires=["populus"] should be enough.

deploy.cd_into_projectpath also won't handle editable installations (pip install -e ...) of the contracts repo. Anybody know why the current installation method for the contracts has been chosen (i.e. install into sys.prefix + "/trustlines-contracts/" ?

**Comment by berndbohmeier** [comment]
I did that. The only goal was to not put the compiled contracts in git, but to build them on installation. If the location is not good and you have a better solution, feel free to change it.

**Comment by berndbohmeier** [comment]
Please open an issue in the contracts repo.

**Comment by schmir** [comment]
I'd rather not waste more time with that. I can't get the installation to work when compiling contracts on installation. 

You have to live with the extra installation step, put the compiled contracts into git, use a source dist with compiled contracts or compile them at runtime, when they are needed.

**Comment by schmir** [comment]
we have trustlines-contracts-bin now. populus does not have to be installed before the installation. it's not even an indirect dependency anymore.
